name = "MyFirstPkg"
uuid = "fa738250-8abf-4da2-88d9-5da9f13b3e46"
authors = ["HoangMHNguyen <m.h.n.hoang@tue.nl> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
